### ISSUE TITLE
Display Character Color icons on owned vehicles on main page

### ISSUE THREAD

**Issue by ADefWebserver** [mytatuo/GTAVehicles#17]
- [x] Alter vw_GTAVehiclesRanked to take a UserID (pass 0 if no user)
- [x] Add a column that contains a comma separated list that contains the Characters that own that vehicle
- [x] In the Stored Procedure, populate the CharactersOwningVehicle column with a comma separated list of users who own that vehicle
- [x] On the index.razor page, in the Radzen Template, call a function that will create the RenderFragment that will create RadzenIcon for each Character that owns the vehicle

**Comment by mytatuo** [comment]
[https://github.com/dotnet/efcore/issues/16991](https://github.com/dotnet/efcore/issues/16991)

Replacing Query<T> and FromSQLRaw
with Set<T> and FromSQLInterpolated
to return results from Stored Procedure

```
public virtual async Task<RawModels.WeatherRecordHighLowSummary> GetWeatherRecordHighLowSummary(DateTimeOffset startRecordDateTime, DateTimeOffset endRecordDateTime)
{
    var result = await this.Set<RawModels.WeatherRecordHighLowSummary>().FromSqlInterpolated($"sp__GetWeatherRecordHighLowSummary {startRecordDateTime}, {endRecordDateTime}")
                .AsNoTracking()
                .ToListAsync();

    return result.SingleOrDefault();
```

**Comment by ADefWebserver** [comment]
![GTADatabaseSchema](https://user-images.githubusercontent.com/1857799/76558819-3576c880-645b-11ea-92db-74b037d5e832.png)

**Comment by ADefWebserver** [comment]
To do: 

Make this query a sub-query that will return a comma separated list that can be a single column in the output of: [sp_GTAVehiclesRankedByUser]

```
SELECT        GTAPlayerVehicles.VehicleID, GTAPlayerCharacters.CharacterName, GTAPlayerCharacters.CharacterColor
FROM            GTAPlayerCharacters INNER JOIN
                         GTAPlayerGarages ON GTAPlayerCharacters.ID = GTAPlayerGarages.CharacterID INNER JOIN
                         GTAPlayerVehicles ON GTAPlayerGarages.ID = GTAPlayerVehicles.PlayerGarageID LEFT OUTER JOIN
                         GTAPlayers ON GTAPlayerCharacters.PlayerID = GTAPlayers.ID
WHERE        (GTAPlayers.UserName = N'webmaster@adefwebserver.com')
```

**Comment by ADefWebserver** [comment]
![Image 3](https://user-images.githubusercontent.com/1857799/76809601-93334980-67a8-11ea-9895-3b6bee59c9ea.png)
