### ISSUE TITLE
BUG - Vehicle counted twice in rankings if owned by multiple characters

### ISSUE THREAD

**Issue by mytatuo** [mytatuo/GTAVehicles#21]
![CountedTwice](https://user-images.githubusercontent.com/55775335/81995921-927c2f80-9600-11ea-8441-fe9c5b0d33b1.png)

Note screenshot, last column.  Because the # 2 van is owned by two characters, it is counted twice in the rankings, so the # 3 is listed as # 4, etc.

**Comment by ADefWebserver** [comment]
The solution would be to alter the stored procedure to output the query (without the rankings) into a temp table using [Richard's Way](http://openlightgroup.com/Blog/TabId/58/PostId/110/Richards-Way-Four-Easy-Steps-To-Create-Complex-SQL-That-Runs-Fast.aspx) and then add the rankings to the final output

**Comment by ADefWebserver** [comment]
To Do

- [x] Make a temp table that just contains the vehicles ranked
- [x] Use that table in the final query
- [x] This way we will have the vehicle ranking number that wont be messed up
